# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ccb25dd1028ec0d0a9f44565ab819ecf44e5ba7afadccaf8dc183c47262b9d9ddb7ca7807a5c27407292f765d40f64965773340be8cf5b3014722aeea6cee0e3

test:
  secret_key_base: 5ec2906dfdc5ef55673c68493a37803696d5d67d5d5fd46781a6664235209b0286a3c9de067385fb5725878916632390ab6ab461d2376f82baa177dfa0fdd959

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
